#!/usr/bin/env bash

###
### Clean all Docker images that might have been generated by
### this stage of processing.
###

# Does tracktable_build_base:latest exist?


BUILD_BASE=$(\
    docker images --format '{{.Repository}}:{{.Tag}}' \
    | grep "tracktable_build_base"
    )

if [ ! -z "${BUILD_BASE}" ]; then
    for image in ${BUILD_BASE}; do
        docker image rm $image
    done
fi
