# Conda environment for readthedocs.io
#
# When we upload documentation to readthedocs, it gets
# built inside a Conda environment.  This file specifies
# that environment's contents.  It is stripped down to
# what we believe is a minimal set of requirements.

name: tracktable-readthedocs
channels:
  - conda-forge
dependencies:
  # Python Dependencies
  - python>=3.10
  - tracktable
  - tracktable-data>=1.7.3
  - pip

  # Jupyter Dependencies
  - ipykernel
  - jupyter

  - nbsphinx
  - doxygen
  - breathe
  - sphinx_rtd_theme

  - pip:
    - nbsphinx-link