# Configuration options for PyTest
#
# We use pytest-cmake to have CTest run our test cases.  You can also run
# `pytest` in the root directory of the repository.

[pytest]
minversion = 6.0

# This is currently being overridden by a bug in pytest-cmake, so we'll
# make do with a bunch of norecursedir statements

testpaths =
   tests/Python/pytest/tests

pythonpath =
    src/Python
    tests/Python/pytest/fixtures
    tracktable-data/tracktable-data

norecursedirs =
    .git
    build*
    tmp*
    *.egg
    .*
    dist
    tests/Python/algorithms
    tests/Python/applications
    tests/Python/core
    tests/Python/data_generators
    tests/Python/domain
    tests/Python/examples
    tests/Python/general
    tests/Python/info
    tests/Python/render
    tests/Python/rw
