# Tracktable Linux CI/CD Anaconda Environment
#
# This environment gets baked into an image built by
# tracktable/ci/linux/Dockerenv/docker-build.sh.
# The image name is set in docker.config in that same
# directory.  It gets picked up by the CI script via
# a GitLab CI environment variable.
#
# See tracktable/ci/linux/README.md for details about
# how to make changes to the environment.

name: tracktable-linux-ci
channels:
  - conda-forge
dependencies:
  # Dev Dependencies
  - git

  # Python Dependencies
  - python
  - pip
  - numpy
  - matplotlib
  - cartopy
  - pytz
  - shapely
  - pyproj
  - folium
  - scipy
  - tqdm
  - tracktable-data>=1.7.3

  # C++ Dependencies
  - compilers
  - libboost-devel>=1.86
  - libboost-python-devel>=1.86
  - libboost-headers>=1.86
  - libboost-python>=1.86
  - cmake>=3.19.5
  - ninja>=1.10.0

  # Jupyter Dependencies
  - ipykernel

  # Movie Dependencies
  - ffmpeg

  # Code Coverage Dependencies
  - lcov
  - coverage

  # Documentation Dependencies
  - sphinx
  - sphinx_rtd_theme
  - nbsphinx
  # conda-forge feedstock is out of date - we need nbsphinx >= 1.3.1
  # - nbsphinx-link>=1.3.0
  - pandoc
  - doxygen
  - graphviz
  - breathe

  # Packaging Dependencies
  - auditwheel
  - unzip
  - twine

  # Static Code Analysis Dependencies
  - mypy
  - mypy_extensions
  - types-six
  - types-pytz
  - flake8
  - pylint
  - cppcheck
  - pygments

  # Repo Badging
  - pip:
      - pylint-exit
      - anybadge
      - nbsphinx-link>=1.3.1