#!/bin/csh

#@ x = 81
#while ($x <= 100)
#     mkdir shape$x
#@ x += 1


cd /space/panther/theory/Geolife/Geolife_Trajectories_1.3/Data/; set dirs=`echo *`
foreach x ($dirs)
cd /space/panther/theory/Geolife/Geolife_Trajectories_1.3/Data/$x/Trajectory
awk -F, -v d=$x 'FNR > 6 {print d"-"FILENAME"\t"$1"\t"$2"\t"$4"\t"$6,$7}' *.plt | dos2unix | sed "s/.plt//" >> /home/mdrinto/src/dev/portal/bliga
end
